#!/bin/bash

set -e

source .env

docker build --progress plain \
--build-arg RELAY_DEPLOYER_PK="${RELAY_DEPLOYER_PK}" \
--build-arg HARDHAT_DYNAMIC_NETWORK_NAME="${HARDHAT_DYNAMIC_NETWORK_NAME}" \
--build-arg HARDHAT_DYNAMIC_NETWORK_URL="${HARDHAT_DYNAMIC_NETWORK_URL}" \
--build-arg HARDHAT_DYNAMIC_NETWORK_CONTRACTS_GELATO="${HARDHAT_DYNAMIC_NETWORK_CONTRACTS_GELATO}" \
--build-arg HARDHAT_DYNAMIC_NETWORK_NO_DETERMINISTIC_DEPLOYMENT="${HARDHAT_DYNAMIC_NETWORK_NO_DETERMINISTIC_DEPLOYMENT}" \
-t "relay-contracts-${HARDHAT_DYNAMIC_NETWORK_NAME}" .

